<?php

namespace Database\Seeders;

use App\Models\Customer;
use App\Models\Company;
use App\Models\Branch;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class CustomerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // ดึงข้อมูล company และ branch ทั้งหมด
        $companies = Company::all();
        $branches = Branch::all();

        $customers = [
            // ==================== ลูกค้าในกรุงเทพ ====================
            [
                'code' => 'CUS-00001',
                'name' => 'ห้างหุ้นส่วนจำกัด พัฒนาเทรดดิ้ง',
                'email' => 'info@pattana-trading.com',
                'phone' => '02-111-2222',
                'address' => '123/45 ถนนสาทรเหนือ แขวงสีลม เขตบางรัก กรุงเทพมหานคร 10500',
                'tax_id' => '0105553001122',
                'contact_person' => 'คุณสมหมาย พัฒนา',
                'contact_phone' => '081-111-2222',
                'is_active' => true,
            ],
            [
                'code' => 'CUS-00002',
                'name' => 'บริษัท สยามอิเล็กทริค จำกัด',
                'email' => 'sales@siam-electric.co.th',
                'phone' => '02-222-3333',
                'address' => '456/78 ถนนพระราม 4 แขวงลุมพินี เขตปทุมวัน กรุงเทพมหานคร 10330',
                'tax_id' => '0105554002233',
                'contact_person' => 'คุณวิชัย ไฟฟ้า',
                'contact_phone' => '082-222-3333',
                'is_active' => true,
            ],
            [
                'code' => 'CUS-00003',
                'name' => 'ร้านทองคำเยาวราช',
                'email' => 'gold@yaowarat.com',
                'phone' => '02-333-4444',
                'address' => '222 ถนนเยาวราช แขวงสัมพันธวงศ์ เขตสัมพันธวงศ์ กรุงเทพมหานคร 10100',
                'tax_id' => '0105555003344',
                'contact_person' => 'คุณทองคำ มีค่า',
                'contact_phone' => '083-333-4444',
                'is_active' => true,
            ],
            [
                'code' => 'CUS-00004',
                'name' => 'บริษัท แอดวานซ์เทค จำกัด',
                'email' => 'contact@advancetech.co.th',
                'phone' => '02-444-5555',
                'address' => '789 อาคารไอทีสแควร์ ถนนแจ้งวัฒนะ แขวงทุ่งสองห้อง เขตหลักสี่ กรุงเทพมหานคร 10210',
                'tax_id' => '0105556004455',
                'contact_person' => 'คุณเทค โนโลยี',
                'contact_phone' => '084-444-5555',
                'is_active' => true,
            ],
            [
                'code' => 'CUS-00005',
                'name' => 'หจก. เจริญยนต์',
                'email' => 'charoen@autopart.com',
                'phone' => '02-555-6666',
                'address' => '345 ถนนพระราม 9 แขวงห้วยขวาง เขตห้วยขวาง กรุงเทพมหานคร 10310',
                'tax_id' => '0105557005566',
                'contact_person' => 'คุณเจริญ รถยนต์',
                'contact_phone' => '085-555-6666',
                'is_active' => true,
            ],

            // ==================== ลูกค้าในชลบุรี/ภาคตะวันออก ====================
            [
                'code' => 'CUS-00006',
                'name' => 'บริษัท ชลบุรีอินดัสทรี จำกัด',
                'email' => 'info@chonburi-industry.com',
                'phone' => '038-111-222',
                'address' => '123 นิคมอุตสาหกรรมแหลมฉบัง ตำบลทุ่งสุขลา อำเภอศรีราชา ชลบุรี 20230',
                'tax_id' => '0205558006677',
                'contact_person' => 'คุณสมชาย โรงงาน',
                'contact_phone' => '086-111-2222',
                'is_active' => true,
            ],
            [
                'code' => 'CUS-00007',
                'name' => 'บริษัท ระยอง ปิโตรเคมี จำกัด',
                'email' => 'info@rayong-petro.com',
                'phone' => '038-222-333',
                'address' => '456 ถนนสุขุมวิท ตำบลเชิงเนิน อำเภอเมืองระยอง ระยอง 21000',
                'tax_id' => '0215559007788',
                'contact_person' => 'คุณประเสริฐ น้ำมัน',
                'contact_phone' => '087-222-3333',
                'is_active' => true,
            ],
            [
                'code' => 'CUS-00008',
                'name' => 'ห้างหุ้นส่วนจำกัด พัทยามารีน',
                'email' => 'pattaya-marine@hotmail.com',
                'phone' => '038-333-444',
                'address' => '789 ถนนพัทยาใต้ ตำบลหนองปรือ อำเภอบางละมุง ชลบุรี 20150',
                'tax_id' => '0205560008899',
                'contact_person' => 'คุณสมศักดิ์ ทะเล',
                'contact_phone' => '088-333-4444',
                'is_active' => true,
            ],
            [
                'code' => 'CUS-00009',
                'name' => 'บริษัท แหลมฉบังโลจิสติกส์ จำกัด',
                'email' => 'info@lcblogistics.com',
                'phone' => '038-444-555',
                'address' => '111 ท่าเรือแหลมฉบัง ตำบลทุ่งสุขลา อำเภอศรีราชา ชลบุรี 20230',
                'tax_id' => '0205561009900',
                'contact_person' => 'คุณสมนึก ขนส่ง',
                'contact_phone' => '089-444-5555',
                'is_active' => true,
            ],
            [
                'code' => 'CUS-00010',
                'name' => 'บริษัท อีสเทิร์นฟู้ด จำกัด',
                'email' => 'sales@easternfood.co.th',
                'phone' => '038-555-666',
                'address' => '222 ถนนบางแสน ตำบลแสนสุข อำเภอเมืองชลบุรี ชลบุรี 20130',
                'tax_id' => '0205562010011',
                'contact_person' => 'คุณอร่อย อาหาร',
                'contact_phone' => '080-555-6666',
                'is_active' => false,
            ],

            // ==================== ลูกค้าในเชียงใหม่/ภาคเหนือ ====================
            [
                'code' => 'CUS-00011',
                'name' => 'บริษัท ล้านนาเทรดดิ้ง จำกัด',
                'email' => 'info@lanna-trading.com',
                'phone' => '053-111-222',
                'address' => '123 ถนนห้วยแก้ว ตำบลสุเทพ อำเภอเมืองเชียงใหม่ เชียงใหม่ 50200',
                'tax_id' => '0505563011122',
                'contact_person' => 'คุณล้านนา วัฒนธรรม',
                'contact_phone' => '081-111-3333',
                'is_active' => true,
            ],
            [
                'code' => 'CUS-00012',
                'name' => 'หจก. เชียงใหม่ไอที',
                'email' => 'cm-it@hotmail.com',
                'phone' => '053-222-333',
                'address' => '456 ถนนนิมมานเหมินทร์ ตำบลสุเทพ อำเภอเมืองเชียงใหม่ เชียงใหม่ 50200',
                'tax_id' => '0505564022233',
                'contact_person' => 'คุณไอที เหนือ',
                'contact_phone' => '082-222-4444',
                'is_active' => true,
            ],
            [
                'code' => 'CUS-00013',
                'name' => 'บริษัท ภูพิงค์รีสอร์ท จำกัด',
                'email' => 'booking@phupingresort.com',
                'phone' => '053-333-444',
                'address' => '789 ถนนแม่ริม ตำบลแม่แรม อำเภอแม่ริม เชียงใหม่ 50180',
                'tax_id' => '0505565033344',
                'contact_person' => 'คุณภูพิงค์ ธรรมชาติ',
                'contact_phone' => '083-333-5555',
                'is_active' => true,
            ],
            [
                'code' => 'CUS-00014',
                'name' => 'ร้านกาแฟอาราบิก้า เชียงราย',
                'email' => 'arabica@chiangrai.com',
                'phone' => '053-444-555',
                'address' => '123 ถนนพ่อขุนเม็งราย ตำบลเวียง อำเภอเมืองเชียงราย เชียงราย 57000',
                'tax_id' => '0575566044455',
                'contact_person' => 'คุณกาแฟ หอมกรุ่น',
                'contact_phone' => '084-444-6666',
                'is_active' => true,
            ],
            [
                'code' => 'CUS-00015',
                'name' => 'บริษัท ลำปางเซรามิค จำกัด',
                'email' => 'info@lampangceramic.com',
                'phone' => '054-111-222',
                'address' => '456 ถนนพหลโยธิน ตำบลชมพู อำเภอเมืองลำปาง ลำปาง 52100',
                'tax_id' => '0525567055566',
                'contact_person' => 'คุณเซรามิค ถ้วยชาม',
                'contact_phone' => '085-555-7777',
                'is_active' => false,
            ],

            // ==================== ลูกค้าในนครราชสีมา/ภาคอีสาน ====================
            [
                'code' => 'CUS-00016',
                'name' => 'หจก. โคราชการเกษตร',
                'email' => 'korat-agri@gmail.com',
                'phone' => '044-111-222',
                'address' => '123 ถนนมิตรภาพ ตำบลในเมือง อำเภอเมืองนครราชสีมา นครราชสีมา 30000',
                'tax_id' => '0305568066677',
                'contact_person' => 'คุณโคราช เกษตรกร',
                'contact_phone' => '086-666-8888',
                'is_active' => true,
            ],
            [
                'code' => 'CUS-00017',
                'name' => 'บริษัท ขอนแก่นมอเตอร์ จำกัด',
                'email' => 'info@kkmotor.com',
                'phone' => '043-111-222',
                'address' => '456 ถนนศรีจันทร์ ตำบลในเมือง อำเภอเมืองขอนแก่น ขอนแก่น 40000',
                'tax_id' => '0405569077788',
                'contact_person' => 'คุณขอนแก่น มอเตอร์ไซค์',
                'contact_phone' => '087-777-9999',
                'is_active' => true,
            ],
            [
                'code' => 'CUS-00018',
                'name' => 'บริษัท อุดรธานีโฮมมาร์ท จำกัด',
                'email' => 'info@udonhomemart.com',
                'phone' => '042-111-222',
                'address' => '789 ถนนอุดรดุษฎี ตำบลหมากแข้ง อำเภอเมืองอุดรธานี อุดรธานี 41000',
                'tax_id' => '0415570088899',
                'contact_person' => 'คุณอุดร บ้านสวย',
                'contact_phone' => '088-888-0000',
                'is_active' => true,
            ],
            [
                'code' => 'CUS-00019',
                'name' => 'หจก. บุรีรัมย์ก่อสร้าง',
                'email' => 'buriram-const@hotmail.com',
                'phone' => '044-222-333',
                'address' => '321 ถนนจิระ ตำบลในเมือง อำเภอเมืองบุรีรัมย์ บุรีรัมย์ 31000',
                'tax_id' => '0315571099900',
                'contact_person' => 'คุณบุรีรัมย์ ก่อสร้าง',
                'contact_phone' => '089-999-1111',
                'is_active' => true,
            ],
            [
                'code' => 'CUS-00020',
                'name' => 'บริษัท อุบลราชธานีการค้า จำกัด',
                'email' => 'info@ubontrade.com',
                'phone' => '045-111-222',
                'address' => '123 ถนนอุปลีสาน ตำบลในเมือง อำเภอเมืองอุบลราชธานี อุบลราชธานี 34000',
                'tax_id' => '0345572011122',
                'contact_person' => 'คุณอุบล ราชธานี',
                'contact_phone' => '080-000-2222',
                'is_active' => true,
            ],

            // ==================== ลูกค้าในภูเก็ต/ภาคใต้ ====================
            [
                'code' => 'CUS-00021',
                'name' => 'บริษัท ภูเก็ตทัวร์ จำกัด',
                'email' => 'info@phukettour.com',
                'phone' => '076-111-222',
                'address' => '123 ถนนเทพกระษัตรี ตำบลรัษฎา อำเภอเมืองภูเก็ต ภูเก็ต 83000',
                'tax_id' => '0835573022233',
                'contact_person' => 'คุณภูเก็ต ท่องเที่ยว',
                'contact_phone' => '081-111-4444',
                'is_active' => true,
            ],
            [
                'code' => 'CUS-00022',
                'name' => 'หจก. สงขลาประมง',
                'email' => 'songkhla-fish@hotmail.com',
                'phone' => '074-111-222',
                'address' => '456 ถนนนครนอก ตำบลบ่อยาง อำเภอเมืองสงขลา สงขลา 90000',
                'tax_id' => '0905574033344',
                'contact_person' => 'คุณสงขลา ประมง',
                'contact_phone' => '082-222-5555',
                'is_active' => true,
            ],
            [
                'code' => 'CUS-00023',
                'name' => 'บริษัท กระบี่รีสอร์ท จำกัด',
                'email' => 'booking@krabiresort.com',
                'phone' => '075-111-222',
                'address' => '123 ถนนมหาราช ตำบลกระบี่ใหญ่ อำเภอเมืองกระบี่ กระบี่ 81000',
                'tax_id' => '0815575044455',
                'contact_person' => 'คุณกระบี่ รีสอร์ท',
                'contact_phone' => '083-333-6666',
                'is_active' => true,
            ],
            [
                'code' => 'CUS-00024',
                'name' => 'หจก. หาดใหญ่การค้า',
                'email' => 'hatyai-trade@gmail.com',
                'phone' => '074-222-333',
                'address' => '789 ถนนนิพัทธ์อุทิศ 1 ตำบลหาดใหญ่ อำเภอหาดใหญ่ สงขลา 90110',
                'tax_id' => '0905576055566',
                'contact_person' => 'คุณหาดใหญ่ ค้าขาย',
                'contact_phone' => '084-444-7777',
                'is_active' => true,
            ],
            [
                'code' => 'CUS-00025',
                'name' => 'บริษัท สุราษฎร์ธานียางพารา จำกัด',
                'email' => 'info@surat-rubber.com',
                'phone' => '077-111-222',
                'address' => '456 ถนนตลาดใหม่ ตำบลตลาด อำเภอเมืองสุราษฎร์ธานี สุราษฎร์ธานี 84000',
                'tax_id' => '0845577066677',
                'contact_person' => 'คุณยางพารา ภาคใต้',
                'contact_phone' => '085-555-8888',
                'is_active' => true,
            ],

            // ==================== ลูกค้าอื่นๆ ทั่วประเทศ ====================
            [
                'code' => 'CUS-00026',
                'name' => 'บริษัท ไทยเบฟเวอเรจ จำกัด (มหาชน)',
                'email' => 'info@thaibev.co.th',
                'phone' => '02-999-8888',
                'address' => '14 ถนนวิภาวดีรังสิต แขวงจอมพล เขตจตุจักร กรุงเทพมหานคร 10900',
                'tax_id' => '0105558077788',
                'contact_person' => 'คุณเครื่องดื่ม ไทย',
                'contact_phone' => '080-999-8888',
                'is_active' => true,
            ],
            [
                'code' => 'CUS-00027',
                'name' => 'บริษัท ซีพี ออลล์ จำกัด (มหาชน)',
                'email' => 'info@cpall.co.th',
                'phone' => '02-888-7777',
                'address' => '313 ถนนสีลม แขวงสีลม เขตบางรัก กรุงเทพมหานคร 10500',
                'tax_id' => '0105559088899',
                'contact_person' => 'คุณซีพี เซเว่น',
                'contact_phone' => '081-888-7777',
                'is_active' => true,
            ],
            [
                'code' => 'CUS-00028',
                'name' => 'บริษัท ปตท. จำกัด (มหาชน)',
                'email' => 'info@pttplc.com',
                'phone' => '02-777-6666',
                'address' => '555 ถนนวิภาวดีรังสิต แขวงจตุจักร เขตจตุจักร กรุงเทพมหานคร 10900',
                'tax_id' => '0105560099900',
                'contact_person' => 'คุณปตท. น้ำมัน',
                'contact_phone' => '082-777-6666',
                'is_active' => true,
            ],
            [
                'code' => 'CUS-00029',
                'name' => 'บริษัท การบินไทย จำกัด (มหาชน)',
                'email' => 'info@thaiairways.com',
                'phone' => '02-666-5555',
                'address' => '89 ถนนวิภาวดีรังสิต เขตจตุจักร กรุงเทพมหานคร 10900',
                'tax_id' => '0105561011122',
                'contact_person' => 'คุณการบิน ไทย',
                'contact_phone' => '083-666-5555',
                'is_active' => true,
            ],
            [
                'code' => 'CUS-00030',
                'name' => 'บริษัท เอไอเอส จำกัด (มหาชน)',
                'email' => 'info@ais.co.th',
                'phone' => '02-555-4444',
                'address' => '414 ถนนพหลโยธิน แขวงสามเสนใน เขตพญาไท กรุงเทพมหานคร 10400',
                'tax_id' => '0105562022233',
                'contact_person' => 'คุณเอไอเอส มือถือ',
                'contact_phone' => '084-555-4444',
                'is_active' => true,
            ],

            // ==================== ลูกค้าเพิ่มเติม (21 รายการ) ====================
            [
                'code' => 'CUS-00031',
                'name' => 'ร้านขายยา ฟาร์มาซี',
                'email' => 'pharmacy@gmail.com',
                'phone' => '02-123-7890',
                'address' => '123 ถนนพญาไท แขวงถนนพญาไท เขตราชเทวี กรุงเทพมหานคร 10400',
                'tax_id' => '0105563033344',
                'contact_person' => 'คุณเภสัช ยารักษา',
                'contact_phone' => '081-123-7890',
                'is_active' => true,
            ],
            [
                'code' => 'CUS-00032',
                'name' => 'บริษัท สมุทรปราการการพิมพ์ จำกัด',
                'email' => 'info@spkprint.com',
                'phone' => '02-234-8901',
                'address' => '456 ถนนศรีนครินทร์ ตำบลสำโรงเหนือ อำเภอเมืองสมุทรปราการ สมุทรปราการ 10270',
                'tax_id' => '0115564044455',
                'contact_person' => 'คุณสมุทร ปราการ',
                'contact_phone' => '086-234-8901',
                'is_active' => true,
            ],
            [
                'code' => 'CUS-00033',
                'name' => 'หจก. นนท์การค้า',
                'email' => 'non-trade@hotmail.com',
                'phone' => '02-345-9012',
                'address' => '789 ถนนรัตนาธิเบศร์ ตำบลบางกระสอ อำเภอเมืองนนทบุรี นนทบุรี 11000',
                'tax_id' => '0125565055566',
                'contact_person' => 'คุณนนท์ การค้า',
                'contact_phone' => '087-345-9012',
                'is_active' => true,
            ],
            [
                'code' => 'CUS-00034',
                'name' => 'บริษัท ปทุมธานีการเกษตร จำกัด',
                'email' => 'info@pttagri.com',
                'phone' => '02-456-0123',
                'address' => '123 ถนนรังสิต-นครนายก ตำบลประชาธิปัตย์ อำเภอธัญบุรี ปทุมธานี 12130',
                'tax_id' => '0135566066677',
                'contact_person' => 'คุณปทุม ธานี',
                'contact_phone' => '088-456-0123',
                'is_active' => true,
            ],
            [
                'code' => 'CUS-00035',
                'name' => 'หจก. นครปฐมโภชนา',
                'email' => 'food-nakhon@gmail.com',
                'phone' => '034-567-1234',
                'address' => '456 ถนนราชมรรคา ตำบลพระปฐมเจดีย์ อำเภอเมืองนครปฐม นครปฐม 73000',
                'tax_id' => '0735567077788',
                'contact_person' => 'คุณนครปฐม อาหาร',
                'contact_phone' => '089-567-1234',
                'is_active' => false,
            ],
            [
                'code' => 'CUS-00036',
                'name' => 'บริษัท อยุธยาอิเล็คทรอนิกส์ จำกัด',
                'email' => 'info@ayutthaya-elec.com',
                'phone' => '035-678-2345',
                'address' => '123 โรจนะ นิคมอุตสาหกรรม ตำบลคานหาม อำเภออุทัย พระนครศรีอยุธยา 13210',
                'tax_id' => '0145568088899',
                'contact_person' => 'คุณอยุธยา อิเล็คทรอนิกส์',
                'contact_phone' => '080-678-2345',
                'is_active' => true,
            ],
            [
                'code' => 'CUS-00037',
                'name' => 'หจก. สระบุรีก่อสร้าง',
                'email' => 'saraburi-const@gmail.com',
                'phone' => '036-789-3456',
                'address' => '456 ถนนมิตรภาพ ตำบลปากเพรียว อำเภอเมืองสระบุรี สระบุรี 18000',
                'tax_id' => '0195569099900',
                'contact_person' => 'คุณสระบุรี ก่อสร้าง',
                'contact_phone' => '081-789-3456',
                'is_active' => true,
            ],
            [
                'code' => 'CUS-00038',
                'name' => 'บริษัท กาญจนบุรีทัวร์ จำกัด',
                'email' => 'info@kanchanaburi-tour.com',
                'phone' => '034-890-4567',
                'address' => '789 ถนนแสงชูโต ตำบลบ้านเหนือ อำเภอเมืองกาญจนบุรี กาญจนบุรี 71000',
                'tax_id' => '0715570011122',
                'contact_person' => 'คุณกาญจนบุรี ท่องเที่ยว',
                'contact_phone' => '082-890-4567',
                'is_active' => true,
            ],
            [
                'code' => 'CUS-00039',
                'name' => 'หจก. เพชรบุรีการไฟฟ้า',
                'email' => 'phetchaburi-elec@hotmail.com',
                'phone' => '032-901-5678',
                'address' => '123 ถนนบ้านแหลม ตำบลท่าราบ อำเภอเมืองเพชรบุรี เพชรบุรี 76000',
                'tax_id' => '0765571022233',
                'contact_person' => 'คุณเพชรบุรี ไฟฟ้า',
                'contact_phone' => '083-901-5678',
                'is_active' => false,
            ],
            [
                'code' => 'CUS-00040',
                'name' => 'บริษัท ประจวบคีรีขันธ์รีสอร์ท จำกัด',
                'email' => 'info@prachuap-resort.com',
                'phone' => '032-012-6789',
                'address' => '456 ถนนเพชรเกษม ตำบลหัวหิน อำเภอหัวหิน ประจวบคีรีขันธ์ 77110',
                'tax_id' => '0775572033344',
                'contact_person' => 'คุณประจวบ รีสอร์ท',
                'contact_phone' => '084-012-6789',
                'is_active' => true,
            ],
            [
                'code' => 'CUS-00041',
                'name' => 'หจก. นครศรีธรรมราชการค้า',
                'email' => 'nakhonsi-trade@gmail.com',
                'phone' => '075-123-7890',
                'address' => '789 ถนนราชดำเนิน ตำบลในเมือง อำเภอเมืองนครศรีธรรมราช นครศรีธรรมราช 80000',
                'tax_id' => '0805573044455',
                'contact_person' => 'คุณนครศรี การค้า',
                'contact_phone' => '085-123-7890',
                'is_active' => true,
            ],
            [
                'code' => 'CUS-00042',
                'name' => 'บริษัท ตรังการยาง จำกัด',
                'email' => 'info@trangrubber.com',
                'phone' => '075-234-8901',
                'address' => '123 ถนนห้วยยอด ตำบลทับเที่ยง อำเภอเมืองตรัง ตรัง 92000',
                'tax_id' => '0925574055566',
                'contact_person' => 'คุณตรัง การยาง',
                'contact_phone' => '086-234-8901',
                'is_active' => true,
            ],
            [
                'code' => 'CUS-00043',
                'name' => 'หจก. พัทลุงประมง',
                'email' => 'phatthalung-fish@hotmail.com',
                'phone' => '074-345-9012',
                'address' => '456 ถนนรามวิถี ตำบลคูหาสวรรค์ อำเภอเมืองพัทลุง พัทลุง 93000',
                'tax_id' => '0935575066677',
                'contact_person' => 'คุณพัทลุง ประมง',
                'contact_phone' => '087-345-9012',
                'is_active' => true,
            ],
            [
                'code' => 'CUS-00044',
                'name' => 'บริษัท ยะลาเทรดดิ้ง จำกัด',
                'email' => 'info@yalatrade.com',
                'phone' => '073-456-0123',
                'address' => '789 ถนนพิพิธภักดี ตำบลสะเตง อำเภอเมืองยะลา ยะลา 95000',
                'tax_id' => '0955576077788',
                'contact_person' => 'คุณยะลา การค้า',
                'contact_phone' => '088-456-0123',
                'is_active' => true,
            ],
            [
                'code' => 'CUS-00045',
                'name' => 'หจก. นราธิวาสการค้า',
                'email' => 'narathiwat-trade@gmail.com',
                'phone' => '073-567-1234',
                'address' => '123 ถนนภูผาภักดี ตำบลบางนาค อำเภอเมืองนราธิวาส นราธิวาส 96000',
                'tax_id' => '0965577088899',
                'contact_person' => 'คุณนราธิวาส การค้า',
                'contact_phone' => '089-567-1234',
                'is_active' => false,
            ],
            [
                'code' => 'CUS-00046',
                'name' => 'บริษัท สกลนครการเกษตร จำกัด',
                'email' => 'info@sakonnakhon-agri.com',
                'phone' => '042-678-2345',
                'address' => '456 ถนนสุขเกษม ตำบลธาตุเชิงชุม อำเภอเมืองสกลนคร สกลนคร 47000',
                'tax_id' => '0475578099900',
                'contact_person' => 'คุณสกลนคร เกษตร',
                'contact_phone' => '080-678-2345',
                'is_active' => true,
            ],
            [
                'code' => 'CUS-00047',
                'name' => 'หจก. นครพนมการค้า',
                'email' => 'nakhonphanom@hotmail.com',
                'phone' => '042-789-3456',
                'address' => '789 ถนนอภิบาลบัญชา ตำบลในเมือง อำเภอเมืองนครพนม นครพนม 48000',
                'tax_id' => '0485579011122',
                'contact_person' => 'คุณนครพนม การค้า',
                'contact_phone' => '081-789-3456',
                'is_active' => true,
            ],
            [
                'code' => 'CUS-00048',
                'name' => 'บริษัท มุกดาหารโลจิสติกส์ จำกัด',
                'email' => 'info@mukdahan-logis.com',
                'phone' => '042-890-4567',
                'address' => '123 ถนนชยางกูร ตำบลมุกดาหาร อำเภอเมืองมุกดาหาร มุกดาหาร 49000',
                'tax_id' => '0495580022233',
                'contact_person' => 'คุณมุกดาหาร ขนส่ง',
                'contact_phone' => '082-890-4567',
                'is_active' => true,
            ],
            [
                'code' => 'CUS-00049',
                'name' => 'หจก. เลยการค้า',
                'email' => 'loei-trade@gmail.com',
                'phone' => '042-901-5678',
                'address' => '456 ถนนเจริญรัฐ ตำบลกุดป่อง อำเภอเมืองเลย เลย 42000',
                'tax_id' => '0425581033344',
                'contact_person' => 'คุณเลย การค้า',
                'contact_phone' => '083-901-5678',
                'is_active' => true,
            ],
            [
                'code' => 'CUS-00050',
                'name' => 'บริษัท หนองคายอินเตอร์เทรด จำกัด',
                'email' => 'info@nongkhai-inter.com',
                'phone' => '042-012-6789',
                'address' => '789 ถนนมีชัย ตำบลในเมือง อำเภอเมืองหนองคาย หนองคาย 43000',
                'tax_id' => '0435582044455',
                'contact_person' => 'คุณหนองคาย การค้า',
                'contact_phone' => '084-012-6789',
                'is_active' => true,
            ],
        ];

        $count = 0;
        foreach ($customers as $customer) {
            // กำหนด branch_id และ company_id ถ้ามี
            if ($branches->isNotEmpty()) {
                $customer['branch_id'] = $branches->random()->id;
            }

            if ($companies->isNotEmpty()) {
                $customer['company_id'] = $companies->random()->id;
            }

            Customer::create($customer);
            $count++;
        }

        $this->command->info("✅ CustomerSeeder: เพิ่มข้อมูลลูกค้า {$count} รายการเรียบร้อยแล้ว");

        // แสดงสรุป
        $this->command->table(
            ['รายการ', 'จำนวน'],
            [
                ['ลูกค้าทั้งหมด', Customer::count()],
                ['เปิดใช้งาน', Customer::where('is_active', true)->count()],
                ['ปิดใช้งาน', Customer::where('is_active', false)->count()],
                ['มีบริษัท', Customer::whereNotNull('company_id')->count()],
                ['มีสาขา', Customer::whereNotNull('branch_id')->count()],
            ]
        );
    }
}
